# Generated by Django 2.2 on 2019-06-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('hr_pega', models.CharField(blank=True, max_length=20)),
                ('hr_deixa', models.CharField(blank=True, max_length=20)),
                ('necessidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Incricao',
        ),
    ]
