# Generated by Django 2.2 on 2019-06-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20190618_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='necessidade',
            new_name='cargo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='hr_deixa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='hr_pega',
        ),
    ]
